DROP DATABASE IF EXISTS AUTOESCOLA;

CREATE DATABASE IF NOT EXISTS AUTOESCOLA;

USE AUTOESCOLA;

CREATE TABLE PESSOA (
	PES_CODIGO  INT AUTO_INCREMENT NOT NULL,
	PES_NOME    VARCHAR (200),
	PES_CPF     VARCHAR (11),
	
	PRIMARY KEY(PES_CODIGO)
);

CREATE TABLE USUARIO (
	USU_CODIGO  INT AUTO_INCREMENT NOT NULL,
	USU_USUARIO VARCHAR(50),
	USU_SENHA   VARCHAR(50),
	USU_TIPO    INT,
	
	PES_CODIGO  INT,
	
	PRIMARY KEY (USU_CODIGO),
	FOREIGN KEY (PES_CODIGO) REFERENCES PESSOA(PES_CODIGO)
);


