USE AUTOESCOLA;

SELECT * FROM PESSOA p 

SELECT * FROM USUARIO u 

DELETE FROM USUARIO;

DELETE FROM PESSOA;


INSERT INTO PESSOA VALUES (1, "Felipe Caue Machado", "09297363970");
INSERT INTO USUARIO VALUES (1, "feh", "123", 2, 1);